config/routes.rb
Rails.application.routes.draw do
  resource :user, only: %i[show edit update]
  resources :blog_entries

  # sessions_controller
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # leeds_controller
  resources :leads
  
  #pages_controller
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  # root page
  root 'blog_entries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_entry.rb
class BlogEntry < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true
end

app/models/lead.rb
class Lead < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :blog_entries, dependent: :destroy
  has_many :leads, dependent: :destroy

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/blog_entries_controller.rb
class BlogEntriesController < ApplicationController
  before_action :set_blog_entry, only: %i[show edit update destroy]
  before_action :require_login, except: %i[index show]

  def index
    @blog_entries = BlogEntry.all
  end

  def show
  end

  def new
    @blog_entry = BlogEntry.new
  end

  def create
    @blog_entry = current_user.blog_entries.build(blog_entry_params)
    if @blog_entry.save
      redirect_to @blog_entry, notice: 'Blog entry was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @blog_entry.update(blog_entry_params)
      redirect_to @blog_entry, notice: 'Blog entry was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @blog_entry.destroy
    redirect_to blog_entries_url, notice: 'Blog entry was successfully destroyed.'
  end

  private

  def set_blog_entry
    @blog_entry = BlogEntry.find(params[:id])
  end

  def blog_entry_params
    params.require(:blog_entry).permit(:title, :content)
  end

  def require_login
    unless logged_in?
      redirect_to login_path, alert: 'Please log in to continue.'
    end
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: [:show, :edit, :update, :destroy]

  def index
    @leads = Lead.all
  end

  def show
  end

  def new
    @lead = Lead.new
  end

  def create
    @lead = Lead.new(lead_params)
    @lead.user_id = User.first.id
    if @lead.save!
      redirect_to @lead, notice: 'Lead was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @lead.update(lead_params)
      redirect_to @lead, notice: 'Lead was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @lead.destroy
    redirect_to leads_url, notice: 'Lead was successfully destroyed.'
  end

  private

  def set_lead
    @lead = Lead.find(params[:id])
  end

  def lead_params
    params.require(:lead).permit(:email, :first_name, :last_name, :message_content, :phone_number, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @greeting = 'Welcome to my technical Blog!'
  end

  def about
    @greeting = "Welcome to the section all about me! Here you'll find my resume, information about me and my social pages."
  end

  def contact
    @greeting = 'Welcome, here is a form where you can reach out and request my services or contact me for any reason you deem necessary.'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in successfully.'
    else
      flash.now[:alert] = 'Invalid username or password.'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out successfully.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update]

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blog_entries/edit.html.erb
<h1 class="form-title">Edit Blog Entry</h1>

<%= form_with(model: @blog_entry, local: true, class: "blog-entry-form") do |form| %>
  <% if @blog_entry.errors.any? %>
    <div id="error_explanation" class="error-explanation">
      <h2><%= pluralize(@blog_entry.errors.count, "error") %> prohibited this blog entry from being saved:</h2>
      <ul>
        <% @blog_entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-input" %>
  </div>

  <div class="field">
    <%= form.label :content, class: "form-label" %>
    <%= form.text_area :content, class: "form-input" %>
  </div>

  <div class="actions">
    <%= form.submit 'Update Blog Entry', class: "form-submit" %>
  </div>
<% end %>

<%= link_to 'Back', blog_entries_path, class: "back-link" %>

app/views/blog_entries/index.html.erb
<h1>Blog Entries</h1>

<table class="blog-entries-table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Excerpt</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @blog_entries.each do |entry| %>
      <tr>
        <td><%= link_to entry.title, blog_entry_path(entry) %></td>
        <td><%= truncate(entry.content, length: 100) %></td>
        <% if logged_in? %>
          <td>
            <%= link_to edit_blog_entry_path(entry) do %>
              <%= image_tag('edit.png', alt: 'Edit', class: 'icon') %>
            <% end %>
            <%= link_to blog_entry_path(entry), method: :delete,data: { "turbo-method": :delete, confirm: 'Are you sure?' }, id: "delete-blog" do %>
              <%= image_tag('trash.png', alt: 'Delete', class: 'icon') %>
            <% end %>
          </td>
        <% else %>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if logged_in? %>
  <%= link_to 'New Blog Entry', new_blog_entry_path, class: 'new-entry-link' %>
<% end %>

app/views/blog_entries/new.html.erb
<h1 class="form-title">New Blog Entry</h1>

<%= form_with(model: @blog_entry, local: true, class: "blog-entry-form") do |form| %>
  <% if @blog_entry.errors.any? %>
    <div id="error_explanation" class="error-explanation">
      <h2><%= pluralize(@blog_entry.errors.count, "error") %> prohibited this blog entry from being saved:</h2>
      <ul>
        <% @blog_entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-input" %>
  </div>

  <div class="field">
    <%= form.label :content, class: "form-label" %>
    <%= form.text_area :content, class: "form-input" %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Blog Entry', class: "form-submit" %>
  </div>
<% end %>

<%= link_to 'Back', blog_entries_path, class: "back-link" %>

app/views/blog_entries/show.html.erb
<div class="blog-entry-container">
  <h1 class="blog-entry-title"><%= @blog_entry.title %></h1>
  
  <div class="hero-image-wrapper">
    <%= image_tag("background.jpg", class: "hero-image") %>
  </div>
  
  <p class="blog-entry-content"><%= simple_format(@blog_entry.content) %></p>

  <div class="blog-entry-actions">
    <% if logged_in? %>
      <%= link_to 'Edit', edit_blog_entry_path(@blog_entry), class: 'blog-entry-action' %>
      <%= link_to 'Delete', @blog_entry, method: :delete, data: { confirm: 'Are you sure?' }, class: 'blog-entry-action' %>
    <% end %>
    <%= link_to 'Back', blog_entries_path, class: 'blog-entry-action' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'home', media: 'all' %>
    <%= stylesheet_link_tag 'blog', media: 'all' %>
    <%= stylesheet_link_tag 'footer', media: 'all' %>
    <%= stylesheet_link_tag 'lead', media: 'all' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="navigation-wrapper">
      <ul id="navigation">
        <li class="nav-items"><a href=<%= home_path %>>Home</a></li>
        <li class="nav-items"><a href=<%= blog_entries_path %>>Blogs</a></li>
        <li class="nav-items"><a href=<%= about_path %>>About</a></li>
        <li class="nav-items"><a href=<%= new_lead_path %>>Contact</a></li>
        <% if logged_in? %> 
          <li class="nav-items"><a href=<%= leads_path %>>Leads</a></li>
        <% end %>
          <div><span id="search-text">Search:</span> <input type="text" class="search-input">
        </div>
      </ul>
    </div>
    <%= yield %>
    <footer class="footer">
      <div class="footer-content">
        <p>&copy; <%= Date.today.year %> James-Ryan's Technical Blog. All rights reserved.</p>
      </div>
    </footer>
  </body>
</html>

app/views/leads/new.html.erb
<div class="form-wrapper">
    <%= form_for @lead do |f| %>
        <h1>Submit Inquiry</h1>
        <div class="input-divs">
            <%= f.text_field :first_name, placeholder: 'First Name', class: 'form-inputs' %>
        </div>
        <div class="input-divs">
            <%= f.text_field :last_name, placeholder: 'Last Name', class: 'form-inputs' %>
        </div>
        <div class="input-divs">
            <%= f.text_field :email, type: 'email', placeholder: "Email (ex: james@gmail.com)", class: 'form-inputs' %>
        </div>
        <div class="input-divs">
            <%= f.text_field :phone_number, type: 'phone', placeholder: "(602)-XXX-XXXX", class: 'form-inputs' %>
        </div>
        <div class="input-divs"> 
            <%= f.text_area :message_content, placeholder: "Enter your reason for reaching out.", class: 'form-inputs' %>
        </div>
        <div class="submit-div">
            <%= f.submit "Create Lead", class: 'submit-button' %>
        </div>
    <% end %>
</div>

app/views/pages/about.html.erb
about me page

app/views/pages/contact.html.erb
contact me page

app/views/pages/home.html.erb
<div id="home-wrapper">
    <h1><%= @greeting %></h1>
    <div id="view-blogs" class="home-sections">
        <img id="hero-image" src="https://placehold.co/600x400" alt="Hero Image">
    </div>

    <div id="view-projects" class="home-sections">
        View Projects
    </div>

    <div id="view-tutoring" class="home-sections">
        Check out Tutoring Services
    </div>
</div>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<%= link_to 'Edit Profile', edit_user_path %>